version: '2'
services:
  backend:
      build: backend 
      ports:
        - "8080:8080"
      depends_on:
        - db
  db:
      image: mysql:5.7
      ports:
        - "3306:3306"
      environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_USER: productadmin
        MYSQL_PASSWORD: pw
        MYSQL_DATABASE: products
  frontend-react:
      container_name: frontend-react
      build:
        context: frontend-react
        dockerfile: Dockerfile
      volumes:
        - '.:/frontend-react'
        - '/frontend-react/node_modules'
      ports:
        - 3000:3000
      environment:
        - CHOKIDAR_USEPOLLING=true
      stdin_open: true
      tty: true


